<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inamsoft.Libs.MetadataProviders\Inamsoft.Libs.MetadataProviders.csproj" />
    <ProjectReference Include="..\Inamsoft.Libs.SourceGenerators.Attributes\Inamsoft.Libs.SourceGenerators.Attributes.csproj" />
    <ProjectReference Include="..\Inamsoft.MediaFileRenamer.Abstractions\Inamsoft.MediaFileRenamer.Abstractions.csproj" />
  </ItemGroup>

</Project>
