using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Inamsoft.Libs.SourceGenerators;

[Generator]
public sealed class OperationMessageGenerator : GeneratorBase, IIncrementalGenerator
{
    private static readonly ImmutableHashSet<string> AllowedPlaceholders =
    ImmutableHashSet.Create("fileName", "fileCount", "source", "destination");

    // Constant definitions for GenerateDictionaryAttribute
    private const string AttributesNamespace = "Inamsoft.Libs.SourceGenerators.Attributes";

    private const string OperationTemplateAttribClassName = "OperationTemplateAttribute";
    private const string OperationTemplateAttribFullName = AttributesNamespace + "." + OperationTemplateAttribClassName;

    private const string TemplateConstantsClassName = "TemplateConstants";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all enum declarations
        var enumDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: static (ctx, _) => (EnumDeclarationSyntax)ctx.Node)
            .Where(static e => e is not null);

        // Combine enum syntax with semantic model
        var enumSymbols = context.CompilationProvider.Combine(enumDeclarations.Collect())
            .SelectMany(static (pair, _) =>
            {
                var (compilation, enums) = pair;
                var list = ImmutableArray.CreateBuilder<INamedTypeSymbol>();

                foreach (var e in enums)
                {
                    var symbol = compilation.GetSemanticModel(e.SyntaxTree).GetDeclaredSymbol(e) as INamedTypeSymbol;
                    if (symbol is not null)
                        list.Add(symbol);
                }

                return list.ToImmutable();
            });

        // Generate output
        context.RegisterSourceOutput(enumSymbols, static (ctx, enumSymbol) =>
        {
            var source = GenerateForEnum(enumSymbol);
            if (source is not null)
            {
                ctx.AddSource($"{enumSymbol.Name}.OperationTemplates.g.cs",
                    SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static string? GenerateForEnum(INamedTypeSymbol enumSymbol)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using Spectre.Console;");
        builder.AppendLine("using Microsoft.Extensions.Logging;");
        builder.AppendLine();
        builder.AppendLine($"// EnumName: {GetSafeTypeName(enumSymbol)}");

        var ns = GetOutputNamespace(enumSymbol);

        var enumMembers = enumSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(m => m.HasConstantValue)
            .ToImmutableArray();

        var enumModel = CreateEnumModel(enumSymbol);
        builder.AppendLine($"// EnumModel: {(enumModel is null ? "null" : "not null")}");
        builder.AppendLine();
        builder.AppendLine($"// Namespace: {enumModel?.Namespace}");
        builder.AppendLine($"// Name: {enumModel?.Name}");
        builder.AppendLine($"// Members Count: {enumModel?.Members.Length ?? 0}");
        builder.AppendLine();
        foreach (var member in enumModel?.Members ?? Enumerable.Empty<MemberModel>())
        {
            builder.AppendLine($"//   Member: {member.Name}, Template: {member.Template}");
            builder.AppendLine($"//           Placeholders: {string.Join(";", member.Placeholders)}");
            builder.AppendLine($"//           InvalidPlaceholders: {string.Join(";", member.InvalidPlaceholders)}");
            builder.AppendLine($"//           Required: {string.Join(";", member.Required)}");
            builder.AppendLine($"//           Optional: {string.Join(";", member.Optional)}");
        }
        builder.AppendLine();

        var markList = new List<(string Name, string Template)>();
        foreach (var member in enumSymbol.GetMembers())
        {
            if (member is not IFieldSymbol field || field.ConstantValue is null)
                continue;

            foreach (var attr in field.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() != OperationTemplateAttribFullName)
                    continue;

                var template = attr.ConstructorArguments[0].Value?.ToString();
                if (template is not null)
                    markList.Add((field.Name, template));
            }
        }

        if (markList.Count == 0)
            return null;

        if (ns is not null)
        {
            builder.AppendLine($"namespace {ns};");
            builder.AppendLine();
        }

        builder.AppendLine($"public static class {enumSymbol.Name}OperationTemplates");
        builder.AppendLine("{");

        // Templates as constants
        GenerateTemplateConstants(builder, enumModel!);
        builder.AppendLine();
        
        // Generate GetTemplate and GetLogTemplate methods
        GenerateGetTemplateMethods(builder, enumModel!);
        builder.AppendLine();

        // Metadata for analyzer & logging
        GenerateAnalyzerAndLoggingMetadata(builder, enumModel!);
        builder.AppendLine();
        
        // Mapping methods
        GenerateStepTextMappingMethod(builder);
        
        // Per-operation context types + methods
        //GeneratePerOperationContextTypes(builder, enumModel!);
        foreach (var member in enumModel!.Members)
        {
            GenerateContextType(builder, member);
            builder.AppendLine();
            
            GenerateFormatterMethods(builder, member);
            builder.AppendLine();
            
            GenerateSpectreFormatterMethods(builder, member);
            builder.AppendLine();
            
            GenerateProgressHelper(builder, member);
            builder.AppendLine();
        }
        
        builder.AppendLine();
        
        // Class close
        builder.AppendLine("}");
        builder.AppendLine();
        
        // Logging extensions
        GenerateLoggingExtension(builder, enumModel!);

        return builder.ToString();
    }

    private static void GenerateLoggingExtension(StringBuilder builder, EnumModel enumModel)
    {
        builder.AppendLine($"public static class {enumModel.Name}OperationTemplatesLoggingExtensions");
        builder.AppendLine("{");
        foreach (var m in enumModel.Members)
        {
            var ctxType = $"{enumModel.Name}OperationTemplates.{m.Name}Context";
            builder.AppendLine($"        public static void Log{m.Name}(this ILogger logger, {ctxType} ctx)");
            builder.AppendLine("        {");
            builder.AppendLine($"            var template = {enumModel.Name}OperationTemplates.GetLogTemplate({enumModel.Name}.{m.Name});");

            // map placeholders to arguments in deterministic order
            var args = string.Join(", ", m.Placeholders.Select(p =>
                p == "fileCount" ? $"ctx.FileCount" : $"ctx.{UpperFirst(p)}"));

            builder.AppendLine($"            logger.LogInformation(template, {args});");
            builder.AppendLine("        }");
            builder.AppendLine();
        }
        builder.AppendLine("    }");
    }


    /// <summary>
    /// 
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="model"></param>
    private static void GenerateTemplateConstants(StringBuilder builder, EnumModel model)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine($"    /// A container used to store the operation template strings as constants for the enum <code>{model.Name}</code>.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine($"    public static class {TemplateConstantsClassName}");
        builder.AppendLine("    {");
        foreach (var member in model.Members)
        {
            var escaped = member.Template.Replace("\"", "\"\"");
            builder.AppendLine($"       public const string {member.Name} = \"{escaped}\";");
        }

        builder.AppendLine("    }");

        builder.AppendLine();
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="enumModel"></param>
    private static void GenerateGetTemplateMethods(StringBuilder builder, EnumModel enumModel)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine($"    /// Gets the template string for the specified {enumModel.Name} value.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine($"    public static string GetTemplate({enumModel.Name} op) => op switch");
        builder.AppendLine("    {");
        foreach (var member in enumModel.Members)
        {
            builder.AppendLine($"        {enumModel.Name}.{member.Name} => {TemplateConstantsClassName}.{member.Name},");
        }
        builder.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(op))");
        builder.AppendLine("    };");
        builder.AppendLine();

        // Structured logging template (no step prefix, just the template)
        builder.AppendLine("    public static string GetLogTemplate(FileOperationType op) => GetTemplate(op);");
        builder.AppendLine();

    }
    
    /// <summary>
    /// 
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="enumModel"></param>
    /// <exception cref="NotImplementedException"></exception>
    private static void GenerateAnalyzerAndLoggingMetadata(StringBuilder builder, EnumModel enumModel)
    {
        builder.AppendLine("    public static class OperationMessagesMetadata");
        builder.AppendLine("    {");
        
        // Placeholders field
        builder.AppendLine($"        public static readonly System.Collections.Generic.Dictionary<{enumModel.Name}, string[]> Placeholders =");
        builder.AppendLine($"            new System.Collections.Generic.Dictionary<{enumModel.Name}, string[]>");
        builder.AppendLine("            {");
        foreach (var member in enumModel.Members)
        {
            if (member.Placeholders.Length > 0)
            {
                var list = string.Join(", ", member.Placeholders.Select(p => $"\"{p}\""));
                builder.AppendLine($"                [{enumModel.Name}.{member.Name}] = new[] {{ {list} }},");
            }
            else
            {
                builder.AppendLine($"                [{enumModel.Name}.{member.Name}] = [],");
            }
        }
        builder.AppendLine("            };");
        // Optional placeholders field
        builder.AppendLine($"        public static readonly System.Collections.Generic.Dictionary<{enumModel.Name}, string[]> Optional =");
        builder.AppendLine($"            new System.Collections.Generic.Dictionary<{enumModel.Name}, string[]>");
        builder.AppendLine("            {");
        foreach (var member in enumModel.Members)
        {
            if (member.Optional.Length > 0)
            {
                var list = string.Join(", ", member.Optional.Select(p => $"\"{p}\""));
                builder.AppendLine($"                [{enumModel.Name}.{member.Name}] = new[] {{ {list} }},");
            }
            else
            {
                builder.AppendLine($"                [{enumModel.Name}.{member.Name}] = [],");
            }
        }
        builder.AppendLine("            };");
        // Required placeholders field
        builder.AppendLine($"        public static readonly System.Collections.Generic.Dictionary<{enumModel.Name}, string[]> Required =");
        builder.AppendLine($"            new System.Collections.Generic.Dictionary<{enumModel.Name}, string[]>");
        builder.AppendLine("            {");
        foreach (var member in enumModel.Members)
        {
            if (member.Required.Length > 0)
            {
                var list = string.Join(", ", member.Required.Select(p => $"\"{p}\""));
                builder.AppendLine($"                [{enumModel.Name}.{member.Name}] = new[] {{ {list} }},");
            }
            else
            {
                builder.AppendLine($"                [{enumModel.Name}.{member.Name}] = [],");
            }
        }
        builder.AppendLine("            };");
        
        // Class ends
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="member"></param>
    private static void GenerateContextType(StringBuilder builder, MemberModel member)
    {
        
        var typeName = $"{member.Name}Context";

        builder.AppendLine($"    public sealed record {typeName}(");
        builder.AppendLine(string.Join(",\n", member.Placeholders.Select(p =>
            p switch
            {
                "fileCount" => "        int FileCount",
                _ => $"        string {UpperFirst(p)}"
            })));
        builder.AppendLine("    );");
        builder.AppendLine();
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="builder"></param>
    private static void GenerateStepTextMappingMethod(StringBuilder builder)
    {
        builder.AppendLine($"    private static string ToString(OperationStep step)");
        builder.AppendLine("    {");
        builder.AppendLine("        var stepText = step switch");
        builder.AppendLine("        {");
        builder.AppendLine("            OperationStep.Begin => \"Begin\",");
        builder.AppendLine("            OperationStep.Finished => \"Finished\",");
        builder.AppendLine("            OperationStep.Skipped => \"Skipped\",");
        builder.AppendLine("            OperationStep.Retrying => \"Retrying\",");
        builder.AppendLine("            OperationStep.Failed => \"Failed\",");
        builder.AppendLine("            _ => step.ToString()");
        builder.AppendLine("        };");
        builder.AppendLine($"        return stepText;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }
    
    /// <summary>
    /// 
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="member"></param>
    private static void GenerateFormatterMethods(StringBuilder builder, MemberModel member)
    {
        var typeName = $"{member.Name}Context";

        builder.AppendLine($"    public static string {member.Name}({typeName} ctx)");
        builder.AppendLine("    {");
        builder.AppendLine($"        var template = GetTemplate(FileOperationType.{member.Name});");

        if (member.Placeholders.Length == 0)
        {
            builder.AppendLine("        return template;");
        }
        else
        {
            builder.Append("        return template");
            foreach (var p in member.Placeholders)
            {
                var prop = p == "fileCount" ? "FileCount" : UpperFirst(p);
                builder.Append($".Replace(\"{{{p}}}\", ctx.{prop}.ToString())");
            }
            builder.AppendLine(";");
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        // Step-aware message
        builder.AppendLine($"    public static string {member.Name}(OperationStep step, {typeName} ctx)");
        builder.AppendLine("    {");
        builder.AppendLine("        var stepText = ToString(step);");
        builder.AppendLine($"        return stepText + \" \" + {member.Name}(ctx);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }
    
    /// <summary>
    /// 
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="member"></param>
    private static void GenerateSpectreFormatterMethods(StringBuilder builder, MemberModel member)
    {
        var typeName = $"{member.Name}Context";

        builder.AppendLine($"    public static string {member.Name}Spectre({typeName} ctx)");
        builder.AppendLine("    {");
        builder.AppendLine($"        var template = GetTemplate(FileOperationType.{member.Name});");

        if (member.Placeholders.Length == 0)
        {
            builder.AppendLine("        return template;");
        }
        else
        {
            builder.Append("        return template");
            foreach (var p in member.Placeholders)
            {
                var prop = p == "fileCount" ? "FileCount" : UpperFirst(p);
                var color = p switch
                {
                    "fileName" => "yellow",
                    "source" => "blue",
                    "destination" => "blue",
                    "fileCount" => "green",
                    _ => "white"
                };
                builder.Append($".Replace(\"{{{p}}}\", $\"[{color}]{{ctx.{prop}}}[/]\")");
            }
            builder.AppendLine(";");
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.AppendLine($"    public static string {member.Name}Spectre(OperationStep step, {typeName} ctx)");
        builder.AppendLine("    {");
        builder.AppendLine("        var stepText = ToString(step);");
        builder.AppendLine($"        return stepText + \" \" + {member.Name}Spectre(ctx);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }
    
    /// <summary>
    /// 
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="member"></param>
    private static void GenerateProgressHelper(StringBuilder builder, MemberModel member)
    {
        var typeName = $"{member.Name}Context";

        builder.AppendLine($"    public static void {member.Name}ProgressTask(ProgressTask task, OperationStep step, {typeName} ctx)");
        builder.AppendLine("    {");
        builder.AppendLine($"        var message = {member.Name}Spectre(step, ctx);");
        builder.AppendLine("        task.Description = message;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static EnumModel? CreateEnumModel(INamedTypeSymbol enumSymbol)
    {
        var members = enumSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(m => m.HasConstantValue)
            .Select(m =>
            {
                var attr = m.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == OperationTemplateAttribFullName);
                if (attr is null)
                    return null;

                var template = attr.ConstructorArguments[0].Value?.ToString() ?? "";
                var placeholders = ExtractPlaceholders(template).ToImmutableArray();
                var invalid = placeholders.Where(p => !AllowedPlaceholders.Contains(p, StringComparer.OrdinalIgnoreCase)).ToImmutableArray();

                var requiredRaw = attr.NamedArguments
                    .FirstOrDefault(kv => kv.Key == "Required").Value.Value?.ToString();
                var optionalRaw = attr.NamedArguments
                    .FirstOrDefault(kv => kv.Key == "Optional").Value.Value?.ToString();

                var required = SplitList(requiredRaw);
                var optional = SplitList(optionalRaw);
                return new MemberModel(m.Name, template, placeholders, invalid, required, optional);
            })
            .Where(m => m is not null)!
            .ToImmutableArray();

        if (members.IsDefaultOrEmpty)
            return null;

        return new EnumModel(enumSymbol.ContainingNamespace.ToDisplayString(), enumSymbol.Name, members!);
    }
    private static ImmutableArray<string> SplitList(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return ImmutableArray<string>.Empty;

        return value!
            .Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(s => s.Trim())
            .Where(s => s.Length > 0)
            .ToImmutableArray();
    }
    private static IEnumerable<string> ExtractPlaceholders(string template)
    {
        int i = 0;
        while (i < template.Length)
        {
            int start = template.IndexOf('{', i);
            if (start < 0) yield break;

            int end = template.IndexOf('}', start + 1);
            if (end < 0) yield break;

            yield return template.Substring(start + 1, end - start - 1);
            i = end + 1;
        }
    }
    private static string UpperFirst(string s)
    {
        if (string.IsNullOrEmpty(s))
            return s;

        if (s.Length == 1)
            return s.ToUpperInvariant();

        return char.ToUpperInvariant(s[0]) + s.Substring(1);
    }    
    private static void Generate(SourceProductionContext context, ImmutableArray<EnumModel> enums)
    {
        if (enums.IsDefaultOrEmpty)
            return;

        // For now we assume a single FileOperationType enum; you can extend to multiple if needed.
        var fileOpEnum = enums.FirstOrDefault(e => e.Name == "FileOperationType");
        if (fileOpEnum is null)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace FileOpsGen;");
        sb.AppendLine();
        sb.AppendLine("public static class OperationMessages");
        sb.AppendLine("{");

        // GetTemplate(FileOperationType)
        sb.AppendLine("    public static string GetTemplate(FileOperationType op) => op switch");
        sb.AppendLine("    {");
        foreach (var m in fileOpEnum.Members)
        {
            var escaped = m.Template.Replace("\"", "\\\"");
            sb.AppendLine($"        FileOperationType.{m.Name} => \"{escaped}\",");
        }
        sb.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(op))");
        sb.AppendLine("    };");
        sb.AppendLine();

        // GetMessage(FileOperationType, OperationStep)
        sb.AppendLine("    public static string GetMessage(FileOperationType op, OperationStep step)");
        sb.AppendLine("    {");
        sb.AppendLine("        var stepText = step switch");
        sb.AppendLine("        {");
        sb.AppendLine("            OperationStep.Begin => \"Begin\",");
        sb.AppendLine("            OperationStep.Finished => \"Finished\",");
        sb.AppendLine("            OperationStep.Skipped => \"Skipped\",");
        sb.AppendLine("            OperationStep.Retrying => \"Retrying\",");
        sb.AppendLine("            OperationStep.Failed => \"Failed\",");
        sb.AppendLine("            _ => step.ToString()");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        return stepText + \" \" + GetTemplate(op);");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        context.AddSource("OperationMessages.g.cs", sb.ToString());
    }

    private sealed record EnumModel(string Namespace, string Name, ImmutableArray<MemberModel> Members);
    private sealed record MemberModel(
        string Name,
        string Template,
        ImmutableArray<string> Placeholders,
        ImmutableArray<string> InvalidPlaceholders,
        ImmutableArray<string> Required,
        ImmutableArray<string> Optional);
}
