using Inamsoft.Libs.SourceGenerators.Attributes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Inamsoft.Libs.SourceGenerators;


//[Generator]
public sealed class AdvancedOperationMessageGenerator : GeneratorBase, IIncrementalGenerator
{
    private static readonly ImmutableHashSet<string> AllowedPlaceholders =
        ImmutableHashSet.Create("fileName", "fileCount", "source", "destination");

    // Constant definitions for GenerateDictionaryAttribute
    private const string AttributesNamespace = "Inamsoft.Libs.SourceGenerators.Attributes";

    private const string OperationTemplateAttribClassName = "OperationTemplateAttribute";
    private const string OperationTemplateAttribFullName = AttributesNamespace + "." + OperationTemplateAttribClassName;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all enum declarations
        var enumDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: static (ctx, _) => (EnumDeclarationSyntax)ctx.Node)
            .Where(static e => e is not null);

        // Combine enum syntax with semantic model
        var enumSymbols = context.CompilationProvider.Combine(enumDeclarations.Collect())
            .SelectMany(static (pair, _) =>
            {
                var (compilation, enums) = pair;
                var list = ImmutableArray.CreateBuilder<INamedTypeSymbol>();

                foreach (var e in enums)
                {
                    var symbol = compilation.GetSemanticModel(e.SyntaxTree).GetDeclaredSymbol(e) as INamedTypeSymbol;
                    if (symbol is not null)
                        list.Add(symbol);
                }

                return list.ToImmutable();
            });

        // Generate output
        context.RegisterSourceOutput(enumSymbols, static (ctx, enumSymbol) =>
        {
            var source = GenerateForEnum(enumSymbol);
            if (source is not null)
            {
                ctx.AddSource($"{enumSymbol.Name}_OperationTemplates.g.cs",
                    SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static string? GenerateForEnum(INamedTypeSymbol enumSymbol)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine($"// EnumName: {GetSafeTypeName(enumSymbol)}");
        
        var ns = GetOutputNamespace(enumSymbol);

        var markList = new List<(string Name, string Template)>();

        foreach (var member in enumSymbol.GetMembers())
        {
            if (member is not IFieldSymbol field || field.ConstantValue is null)
                continue;

            foreach (var attr in field.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() != OperationTemplateAttribFullName) 
                    continue;
                
                var template = attr.ConstructorArguments[0].Value?.ToString();
                if (template is not null)
                    markList.Add((field.Name, template));
            }
        }

        if (markList.Count == 0)
            return null;

        if (ns is not null)
        {
            builder.AppendLine($"namespace {ns};");
            builder.AppendLine();
        }

        builder.AppendLine($"public static class OperationTemplates_{enumSymbol.Name}");
        builder.AppendLine("{");

        // Constants
        foreach (var (name, template) in markList)
        {
            var escaped = template.Replace("\"", "\"\"");
            builder.AppendLine($"    public const string {name} = \"{escaped}\";");
        }

        builder.AppendLine();
        var enumTypeName = GetSafeTypeName(enumSymbol);

        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Gets the template string for the specified operation type.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine($"    public static string GetTemplate({enumTypeName} op) => op switch");
        builder.AppendLine("    {");
        foreach (var (name, template) in markList)
        {
            var escaped = template.Replace("\"", "\\\"");
            //builder.AppendLine($"        FileOperationType.{name} => \"{escaped}\",");
            builder.AppendLine($"        {enumTypeName}.{name} => {name},");
        }
        builder.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(op))");
        builder.AppendLine("    };");
        builder.AppendLine();

        // Structured logging template (no step prefix, just the template)
        builder.AppendLine("    public static string GetLogTemplate(FileOperationType op) => GetTemplate(op);");
        builder.AppendLine();

        // Metadata for analyzer & logging
        builder.AppendLine("    public static class OperationMessagesMetadata");
        builder.AppendLine("    {");
        builder.AppendLine("        public static readonly System.Collections.Generic.Dictionary<FileOperationType, string[]> Placeholders =");
        builder.AppendLine("            new System.Collections.Generic.Dictionary<FileOperationType, string[]>");
        builder.AppendLine("            {");
        foreach (var (name, template) in markList)
        {
            var placeholders = ExtractPlaceholders(template).ToList();
            if (placeholders.Count > 0)
            {
                var list = string.Join(", ", placeholders.Select(p => $"\"{p}\""));
                builder.AppendLine($"                [{enumTypeName}.{name}] = new[] {{ {list} }},");
            }
            else
            {
                builder.AppendLine($"                [{enumTypeName}.{name}] = [],");
            }
        }
        builder.AppendLine("            };");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.AppendLine("}");

        return builder.ToString();
    }



    private static string GenerateCode(SourceProductionContext context, ImmutableArray<EnumModel> enums, INamedTypeSymbol typeSymbol)
    {
        var outputNamespace = GetOutputNamespace(typeSymbol);
        var typeName = GetSymbolTypeName(typeSymbol);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");

        if (enums.IsDefaultOrEmpty)
            return builder.ToString();

        var fileOpEnum = enums.FirstOrDefault(e => e.Name == "FileOperationType");
        if (fileOpEnum is null)
            return builder.ToString();

        builder.AppendLine("using System;");
        builder.AppendLine("using Spectre.Console;");
        builder.AppendLine();
        builder.AppendLine("namespace FileOpsGen;");
        builder.AppendLine();
        builder.AppendLine("public static class OperationMessages");
        builder.AppendLine("{");

        // Commented warnings for invalid placeholders
        foreach (var m in fileOpEnum.Members)
        {
            foreach (var invalid in m.InvalidPlaceholders)
            {
                builder.AppendLine($"    // WARNING: Invalid placeholder '{{{invalid}}}' in {m.Name}");
            }
        }
        builder.AppendLine();

        // GetTemplate
        builder.AppendLine("    public static string GetTemplate(FileOperationType op) => op switch");
        builder.AppendLine("    {");
        foreach (var m in fileOpEnum.Members)
        {
            var escaped = m.Template.Replace("\"", "\\\"");
            builder.AppendLine($"        FileOperationType.{m.Name} => \"{escaped}\",");
        }
        builder.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(op))");
        builder.AppendLine("    };");
        builder.AppendLine();

        // Structured logging template (no step prefix, just the template)
        builder.AppendLine("    public static string GetLogTemplate(FileOperationType op) => GetTemplate(op);");
        builder.AppendLine();

        // Metadata for analyzer & logging
        builder.AppendLine("    public static class OperationMessagesMetadata");
        builder.AppendLine("    {");
        builder.AppendLine("        public static readonly System.Collections.Generic.Dictionary<FileOperationType, string[]> Placeholders =");
        builder.AppendLine("            new System.Collections.Generic.Dictionary<FileOperationType, string[]>");
        builder.AppendLine("            {");
        foreach (var m in fileOpEnum.Members)
        {
            var list = string.Join(", ", m.Placeholders.Select(p => $"\"{p}\""));
            builder.AppendLine($"                [FileOperationType.{m.Name}] = new[] {{ {list} }},");
        }
        builder.AppendLine("            };");
        builder.AppendLine();
        builder.AppendLine("        public static readonly System.Collections.Generic.Dictionary<FileOperationType, string[]> Required =");
        builder.AppendLine("            new System.Collections.Generic.Dictionary<FileOperationType, string[]>");
        builder.AppendLine("            {");
        foreach (var m in fileOpEnum.Members)
        {
            var list = string.Join(", ", m.Required.Select(p => $"\"{p}\""));
            builder.AppendLine($"                [FileOperationType.{m.Name}] = new[] {{ {list} }},");
        }
        builder.AppendLine("            };");
        builder.AppendLine();
        builder.AppendLine("        public static readonly System.Collections.Generic.Dictionary<FileOperationType, string[]> Optional =");
        builder.AppendLine("            new System.Collections.Generic.Dictionary<FileOperationType, string[]>");
        builder.AppendLine("            {");
        foreach (var m in fileOpEnum.Members)
        {
            var list = string.Join(", ", m.Optional.Select(p => $"\"{p}\""));
            builder.AppendLine($"                [FileOperationType.{m.Name}] = new[] {{ {list} }},");
        }
        builder.AppendLine("            };");
        builder.AppendLine("    }");
        builder.AppendLine();



        // Per-operation context types + methods
        foreach (var m in fileOpEnum.Members)
        {
            GenerateContextType(builder, m);
            GenerateFormatterMethods(builder, m);
            GenerateSpectreFormatterMethods(builder, m);
            GenerateProgressHelper(builder, m);
        }

        builder.AppendLine();
        builder.AppendLine("    public static class OperationLoggingExtensions");
        builder.AppendLine("    {");
        foreach (var m in fileOpEnum.Members)
        {
            var ctxType = $"{m.Name}Context";
            builder.AppendLine($"        public static void Log{m.Name}(this Microsoft.Extensions.Logging.ILogger logger, {ctxType} ctx)");
            builder.AppendLine("        {");
            builder.AppendLine($"            var template = OperationMessages.GetLogTemplate(FileOperationType.{m.Name});");

            // map placeholders to arguments in deterministic order
            var args = string.Join(", ", m.Placeholders.Select(p =>
                p == "fileCount" ? $"ctx.FileCount" : $"ctx.{UpperFirst(p)}"));

            builder.AppendLine($"            logger.LogInformation(template, {args});");
            builder.AppendLine("        }");
            builder.AppendLine();
        }
        builder.AppendLine("    }");

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static EnumModel? GetEnumModel(GeneratorSyntaxContext ctx)
    {
        var enumDecl = (EnumDeclarationSyntax)ctx.Node;
        var enumSymbol = ctx.SemanticModel.GetDeclaredSymbol(enumDecl) as INamedTypeSymbol;
        if (enumSymbol is null)
            return null;

        var members = new List<MemberModel>();

        foreach (var member in enumSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            var attr = member.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == OperationTemplateAttribFullName);

            if (attr is null)
                continue;

            var template = attr.ConstructorArguments[0].Value?.ToString() ?? "";
            var placeholders = ExtractPlaceholders(template).ToImmutableArray();
            var invalid = placeholders.Where(p => !AllowedPlaceholders.Contains(p)).ToImmutableArray();

            var requiredRaw = attr.NamedArguments
                .FirstOrDefault(kv => kv.Key == "Required").Value.Value?.ToString();
            var optionalRaw = attr.NamedArguments
                .FirstOrDefault(kv => kv.Key == "Optional").Value.Value?.ToString();

            var required = SplitList(requiredRaw);
            var optional = SplitList(optionalRaw);

            members.Add(new MemberModel(member.Name, template, placeholders, invalid, required, optional));
        }

        if (members.Count == 0)
            return null;

        return new EnumModel(enumSymbol.ContainingNamespace.ToDisplayString(), enumSymbol.Name, members.ToImmutableArray());
    }

    private static IEnumerable<string> ExtractPlaceholders(string template)
    {
        int i = 0;
        while (i < template.Length)
        {
            int start = template.IndexOf('{', i);
            if (start < 0) yield break;

            int end = template.IndexOf('}', start + 1);
            if (end < 0) yield break;

            yield return template.Substring(start + 1, end - start - 1);
            i = end + 1;
        }
    }

    private static ImmutableArray<string> SplitList(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return ImmutableArray<string>.Empty;

        return value!
            .Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(s => s.Trim())
            .Where(s => s.Length > 0)
            .ToImmutableArray();
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<EnumModel> enums)
    {
        if (enums.IsDefaultOrEmpty)
            return;

        var fileOpEnum = enums.FirstOrDefault(e => e.Name == "FileOperationType");
        if (fileOpEnum is null)
            return;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using System;");
        builder.AppendLine("using Spectre.Console;");
        builder.AppendLine();
        builder.AppendLine("namespace FileOpsGen;");
        builder.AppendLine();
        builder.AppendLine("public static class OperationMessages");
        builder.AppendLine("{");

        // Commented warnings for invalid placeholders
        foreach (var m in fileOpEnum.Members)
        {
            foreach (var invalid in m.InvalidPlaceholders)
            {
                builder.AppendLine($"    // WARNING: Invalid placeholder '{{{invalid}}}' in {m.Name}");
            }
        }
        builder.AppendLine();

        // GetTemplate
        builder.AppendLine("    public static string GetTemplate(FileOperationType op) => op switch");
        builder.AppendLine("    {");
        foreach (var m in fileOpEnum.Members)
        {
            var escaped = m.Template.Replace("\"", "\\\"");
            builder.AppendLine($"        FileOperationType.{m.Name} => \"{escaped}\",");
        }
        builder.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(op))");
        builder.AppendLine("    };");
        builder.AppendLine();

        // Structured logging template (no step prefix, just the template)
        builder.AppendLine("    public static string GetLogTemplate(FileOperationType op) => GetTemplate(op);");
        builder.AppendLine();

        // Metadata for analyzer & logging
        builder.AppendLine("    public static class OperationMessagesMetadata");
        builder.AppendLine("    {");
        builder.AppendLine("        public static readonly System.Collections.Generic.Dictionary<FileOperationType, string[]> Placeholders =");
        builder.AppendLine("            new System.Collections.Generic.Dictionary<FileOperationType, string[]>");
        builder.AppendLine("            {");
        foreach (var m in fileOpEnum.Members)
        {
            var list = string.Join(", ", m.Placeholders.Select(p => $"\"{p}\""));
            builder.AppendLine($"                [FileOperationType.{m.Name}] = new[] {{ {list} }},");
        }
        builder.AppendLine("            };");
        builder.AppendLine();
        builder.AppendLine("        public static readonly System.Collections.Generic.Dictionary<FileOperationType, string[]> Required =");
        builder.AppendLine("            new System.Collections.Generic.Dictionary<FileOperationType, string[]>");
        builder.AppendLine("            {");
        foreach (var m in fileOpEnum.Members)
        {
            var list = string.Join(", ", m.Required.Select(p => $"\"{p}\""));
            builder.AppendLine($"                [FileOperationType.{m.Name}] = new[] {{ {list} }},");
        }
        builder.AppendLine("            };");
        builder.AppendLine();
        builder.AppendLine("        public static readonly System.Collections.Generic.Dictionary<FileOperationType, string[]> Optional =");
        builder.AppendLine("            new System.Collections.Generic.Dictionary<FileOperationType, string[]>");
        builder.AppendLine("            {");
        foreach (var m in fileOpEnum.Members)
        {
            var list = string.Join(", ", m.Optional.Select(p => $"\"{p}\""));
            builder.AppendLine($"                [FileOperationType.{m.Name}] = new[] {{ {list} }},");
        }
        builder.AppendLine("            };");
        builder.AppendLine("    }");
        builder.AppendLine();



        // Per-operation context types + methods
        foreach (var m in fileOpEnum.Members)
        {
            GenerateContextType(builder, m);
            GenerateFormatterMethods(builder, m);
            GenerateSpectreFormatterMethods(builder, m);
            GenerateProgressHelper(builder, m);
        }

        builder.AppendLine();
        builder.AppendLine("    public static class OperationLoggingExtensions");
        builder.AppendLine("    {");
        foreach (var m in fileOpEnum.Members)
        {
            var ctxType = $"{m.Name}Context";
            builder.AppendLine($"        public static void Log{m.Name}(this Microsoft.Extensions.Logging.ILogger logger, {ctxType} ctx)");
            builder.AppendLine("        {");
            builder.AppendLine($"            var template = OperationMessages.GetLogTemplate(FileOperationType.{m.Name});");

            // map placeholders to arguments in deterministic order
            var args = string.Join(", ", m.Placeholders.Select(p =>
                p == "fileCount" ? $"ctx.FileCount" : $"ctx.{UpperFirst(p)}"));

            builder.AppendLine($"            logger.LogInformation(template, {args});");
            builder.AppendLine("        }");
            builder.AppendLine();
        }
        builder.AppendLine("    }");

        builder.AppendLine("}");

        context.AddSource("OperationMessages.g.cs", builder.ToString());
    }

    private static void GenerateContextType(StringBuilder builder, MemberModel m)
    {
        var typeName = $"{m.Name}Context";

        builder.AppendLine($"    public sealed record {typeName}(");
        builder.AppendLine(string.Join(",\n", m.Placeholders.Select(p =>
            p switch
            {
                "fileCount" => "        int FileCount",
                _ => $"        string {UpperFirst(p)}"
            })));
        builder.AppendLine("    );");
        builder.AppendLine();
    }

    private static void GenerateFormatterMethods(StringBuilder builder, MemberModel m)
    {
        var typeName = $"{m.Name}Context";

        builder.AppendLine($"    public static string {m.Name}({typeName} ctx)");
        builder.AppendLine("    {");
        builder.AppendLine($"        var template = GetTemplate(FileOperationType.{m.Name});");

        if (m.Placeholders.Length == 0)
        {
            builder.AppendLine("        return template;");
        }
        else
        {
            builder.Append("        return template");
            foreach (var p in m.Placeholders)
            {
                var prop = p == "fileCount" ? "FileCount" : UpperFirst(p);
                builder.Append($".Replace(\"{{{p}}}\", ctx.{prop}.ToString())");
            }
            builder.AppendLine(";");
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        // Step-aware message
        builder.AppendLine($"    public static string {m.Name}(OperationStep step, {typeName} ctx)");
        builder.AppendLine("    {");
        builder.AppendLine("        var stepText = step switch");
        builder.AppendLine("        {");
        builder.AppendLine("            OperationStep.Begin => \"Begin\",");
        builder.AppendLine("            OperationStep.Finished => \"Finished\",");
        builder.AppendLine("            OperationStep.Skipped => \"Skipped\",");
        builder.AppendLine("            OperationStep.Retrying => \"Retrying\",");
        builder.AppendLine("            OperationStep.Failed => \"Failed\",");
        builder.AppendLine("            _ => step.ToString()");
        builder.AppendLine("        };");
        builder.AppendLine($"        return stepText + \" \" + {m.Name}(ctx);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateSpectreFormatterMethods(StringBuilder builder, MemberModel member)
    {
        var typeName = $"{member.Name}Context";

        builder.AppendLine($"    public static string {member.Name}Spectre({typeName} ctx)");
        builder.AppendLine("    {");
        builder.AppendLine($"        var template = GetTemplate(FileOperationType.{member.Name});");

        if (member.Placeholders.Length == 0)
        {
            builder.AppendLine("        return template;");
        }
        else
        {
            builder.Append("        return template");
            foreach (var p in member.Placeholders)
            {
                var prop = p == "fileCount" ? "FileCount" : UpperFirst(p);
                var color = p switch
                {
                    "fileName" => "yellow",
                    "source" => "blue",
                    "destination" => "blue",
                    "fileCount" => "green",
                    _ => "white"
                };
                builder.Append($".Replace(\"{{{p}}}\", $\"[{color}]{{ctx.{prop}}}[/]\")");
            }
            builder.AppendLine(";");
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.AppendLine($"    public static string {member.Name}Spectre(OperationStep step, {typeName} ctx)");
        builder.AppendLine("    {");
        builder.AppendLine("        var stepText = step switch");
        builder.AppendLine("        {");
        builder.AppendLine("            OperationStep.Begin => \"Begin\",");
        builder.AppendLine("            OperationStep.Finished => \"Finished\",");
        builder.AppendLine("            OperationStep.Skipped => \"Skipped\",");
        builder.AppendLine("            OperationStep.Retrying => \"Retrying\",");
        builder.AppendLine("            OperationStep.Failed => \"Failed\",");
        builder.AppendLine("            _ => step.ToString()");
        builder.AppendLine("        };");
        builder.AppendLine($"        return stepText + \" \" + {member.Name}Spectre(ctx);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void GenerateProgressHelper(StringBuilder builder, MemberModel member)
    {
        var typeName = $"{member.Name}Context";

        builder.AppendLine($"    public static void {member.Name}ProgressTask(ProgressTask task, OperationStep step, {typeName} ctx)");
        builder.AppendLine("    {");
        builder.AppendLine($"        var message = {member.Name}Spectre(step, ctx);");
        builder.AppendLine("        task.Description = message;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static string UpperFirst(string s)
    {
        if (string.IsNullOrEmpty(s))
            return s;

        if (s.Length == 1)
            return s.ToUpperInvariant();

        return char.ToUpperInvariant(s[0]) + s.Substring(1);
    }

    private sealed record EnumModel(string Namespace, string Name, ImmutableArray<MemberModel> Members);
    private sealed record MemberModel(
        string Name,
        string Template,
        ImmutableArray<string> Placeholders,
        ImmutableArray<string> InvalidPlaceholders,
        ImmutableArray<string> Required,
        ImmutableArray<string> Optional);
}
