using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Inamsoft.Libs.SourceGenerators;

[Generator]
public sealed class OperationMessageGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enumDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is EnumDeclarationSyntax eds && eds.AttributeLists.Count > 0,
                transform: static (ctx, _) =>
                {
                    var enumDecl = (EnumDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(enumDecl) as INamedTypeSymbol;
                    return symbol;
                })
            .Where(static s => s is not null)!;

        var enumsWithTemplates = enumDeclarations
            .Select(static (enumSymbol, _) => CreateEnumModel(enumSymbol!))
            .Where(static m => m is not null)!;

        context.RegisterSourceOutput(enumsWithTemplates.Collect(), Generate);
    }

    private static EnumModel? CreateEnumModel(INamedTypeSymbol enumSymbol)
    {
        var members = enumSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(m => m.HasConstantValue)
            .Select(m =>
            {
                var attr = m.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "FileOpsGen.OperationTemplateAttribute");
                if (attr is null)
                    return null;

                var template = attr.ConstructorArguments[0].Value?.ToString() ?? string.Empty;
                return new MemberModel(m.Name, template);
            })
            .Where(m => m is not null)!
            .ToImmutableArray();

        if (members.IsDefaultOrEmpty)
            return null;

        return new EnumModel(enumSymbol.ContainingNamespace.ToDisplayString(), enumSymbol.Name, members);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<EnumModel> enums)
    {
        if (enums.IsDefaultOrEmpty)
            return;

        // For now we assume a single FileOperationType enum; you can extend to multiple if needed.
        var fileOpEnum = enums.FirstOrDefault(e => e.Name == "FileOperationType");
        if (fileOpEnum is null)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace FileOpsGen;");
        sb.AppendLine();
        sb.AppendLine("public static class OperationMessages");
        sb.AppendLine("{");

        // GetTemplate(FileOperationType)
        sb.AppendLine("    public static string GetTemplate(FileOperationType op) => op switch");
        sb.AppendLine("    {");
        foreach (var m in fileOpEnum.Members)
        {
            var escaped = m.Template.Replace("\"", "\\\"");
            sb.AppendLine($"        FileOperationType.{m.Name} => \"{escaped}\",");
        }
        sb.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(op))");
        sb.AppendLine("    };");
        sb.AppendLine();

        // GetMessage(FileOperationType, OperationStep)
        sb.AppendLine("    public static string GetMessage(FileOperationType op, OperationStep step)");
        sb.AppendLine("    {");
        sb.AppendLine("        var stepText = step switch");
        sb.AppendLine("        {");
        sb.AppendLine("            OperationStep.Begin => \"Begin\",");
        sb.AppendLine("            OperationStep.Finished => \"Finished\",");
        sb.AppendLine("            OperationStep.Skipped => \"Skipped\",");
        sb.AppendLine("            OperationStep.Retrying => \"Retrying\",");
        sb.AppendLine("            OperationStep.Failed => \"Failed\",");
        sb.AppendLine("            _ => step.ToString()");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        return stepText + \" \" + GetTemplate(op);");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        context.AddSource("OperationMessages.g.cs", sb.ToString());
    }

    private sealed record EnumModel(string Namespace, string Name, ImmutableArray<MemberModel> Members);
    private sealed record MemberModel(string Name, string Template);
}
